# TP 2

Autor: Baldezzari Lucas

Nota: Parte del código implementado fue otorgado por los docentes del curso.

In [1]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as plt

In [ ]:
#Cargo datos
data = pd.read_csv("download/ath.csv")
#print(data.head())

In [3]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

data.describe()

,nt_proportion0,nt_proportion1,nt_proportion2,nt_proportion3,dinucleotide_proportion0,dinucleotide_proportion1,dinucleotide_proportion2,dinucleotide_proportion3,dinucleotide_proportion4,dinucleotide_proportion5,...,efe,ensemble_frequency,diversity,mfe_efe_difference,dQ,dG,mfei1,mfei2,mfei4,CLASS
count,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,...,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000,1355663.00000
mean,0.31450,0.17009,0.18436,0.33104,0.11099,0.04861,0.05925,0.09472,0.05914,0.03002,...,-17.49897,0.12496,11.07128,0.01874,0.39039,-0.19550,-0.56245,-0.06677,-0.66674,0.00022
std,0.07524,0.06152,0.06307,0.07560,0.05847,0.02564,0.03014,0.04164,0.02900,0.02618,...,6.67495,0.11306,6.48572,0.00656,0.21590,0.07144,0.23269,0.03608,0.20415,0.01497
min,0.00000,0.00549,0.00000,0.01942,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,-473.32000,0.00000,0.18000,0.00047,0.00282,-1.00558,-43.80000,-1.00558,-2.20612,0.00000
25%,0.26087,0.12658,0.14000,0.27723,0.06818,0.02985,0.03798,0.06494,0.03846,0.01205,...,-20.99000,0.04389,6.28000,0.01403,0.22896,-0.23857,-0.64634,-0.08077,-0.79565,0.00000
50%,0.31111,0.16667,0.18072,0.32857,0.10280,0.04651,0.05634,0.09091,0.05714,0.02564,...,-16.61000,0.09039,9.65000,0.01841,0.34516,-0.18902,-0.54483,-0.05926,-0.65455,0.00000
75%,0.36508,0.20988,0.22500,0.38235,0.14516,0.06452,0.07792,0.11966,0.07792,0.04412,...,-12.97000,0.17044,14.44000,0.02305,0.50871,-0.14474,-0.45000,-0.04343,-0.52258,0.00000
max,0.68627,0.55372,0.61719,0.69136,0.50820,0.25000,0.39831,0.50000,0.27586,0.34314,...,-1.37000,0.93584,92.44000,0.05700,2.43709,-0.00105,-0.00588,-0.00035,-0.00556,1.00000

In [7]:
casos = 5000

# Definimos una probabilidad de muestreo de forma tal que sea mucho mas probable
# muestrear un caso positivo que uno negativo
ratio = sum(data["CLASS"])/len(data)
data["weight"] = data["CLASS"].apply(lambda x: ratio if x==0 else 1)

data = data.sample(n = casos, weights=data["weight"]) #nos quedamos con la candidad de casos deseados

data["CLASS"].value_counts()

0    4696
1     304
Name: CLASS, dtype: int64

###  <span style="color: red;">Consulta</span>

Hemos cambiado la forma de mostrar mostrar los datos a solo 2 decimales. Por otro lado, el ratio calculado da aproximadamente _0.00022424_, por lo tanto, al aplicar _'display.float_format'_ estamos perdiendo información ya que para los casos _x==0_ veremos todos 0.00 en vez de ver el valor de _ratio_ realmente. De todos modos, a fines prácticos una probabilidad de 0.00224% podemos considerarla como 0, pero no me queda claro el por qué aplicar

```python
lambda x: ratio if x==0 else 1
```

 si ya tenemos valores cero en CLASS.

In [8]:
X = data.drop(columns=["sequence_names", "CLASS", "weight"]).values
y = data["CLASS"].values
print(X.shape, y.shape)

(5000, 77) (5000,)

### Validación cruzada

Haremos una validación cruzada de 5 particiones, las hacemos acá para que todas las pruebas se corran con los mismo datos. Como los datos estan muy desbalanceados, haremos una partición *estratificada*: cada partición tendrá la misma proporción de clases que los datos originales

In [10]:
from sklearn.model_selection import StratifiedKFold

generador_particiones = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)

particiones = list(generador_particiones.split(X, y))